# Seed Data for Planit Staff Register - Perth, WA
Employee.create(division: 'Technical', name: 'Herminio Vazquez', email: 'hvazquez@planit.net.au', mobile: '+61424242512', title: 'PTTC', role: 'Principal Technical Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('October 21, 2013'))
Employee.create(division: 'Technical', name: 'Kedar Kulkarni', email: 'kkulkarni@planit.net.au', mobile: '+61861093800', title: 'TTC', role: 'Technical Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('October 20, 2014'))
Employee.create(division: 'Technical', name: 'Graham Weston', email: 'gweston@planit.net.au', mobile: '+61861093800', title: 'TTC', role: 'Technical Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('February 10, 2014'))
Employee.create(division: 'Technical', name: 'Brad Arthur', email: 'barthur@planit.net.au', mobile: '+61861093800', title: 'TTC', role: 'Technical Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('August 11, 2014'))
Employee.create(division: 'Technical', name: 'Eric Lim', email: 'elim@planit.net.au', mobile: '+61861093800', title: 'TTC', role: 'Technical Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('September 1, 2014'))
Employee.create(division: 'Technical', name: 'Oleg Kobets', email: 'okobets@planit.net.au', mobile: '+61861093800', title: 'TTC', role: 'Technical Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('March 31, 2014'))
Employee.create(division: 'Technical', name: 'Mary Ann Nakpil', email: 'mnakpil@planit.net.au', mobile: '+61861093800', title: 'TTL', role: 'Technical Test Lead', assigned: false, active: true, joined_company_at: Date.parse('January 12, 2015'))
Employee.create(division: 'Technical', name: 'Jovert Saulon', email: 'jsaulon@planit.net.au', mobile: '+61861093800', title: 'TTL', role: 'Technical Test Lead', assigned: false, active: true, joined_company_at: Date.parse('April 20, 2015'))
Employee.create(division: 'Technical', name: 'Kai Heath', email: 'kheath@planit.net.au', mobile: '+61861093800', title: 'STTA', role: 'Senior Technical Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('October 7, 2013'))
Employee.create(division: 'Technical', name: 'Jackielyn Custodio', email: 'jcustodio@planit.net.au', mobile: '+61861093800', title: 'STTA', role: 'Senior Technical Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('August 25, 2014'))
Employee.create(division: 'Technical', name: 'Leonard Provido', email: 'lprovido@planit.net.au', mobile: '+61861093800', title: 'STTA', role: 'Senior Technical Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('June 3, 2014'))
Employee.create(division: 'Technical', name: 'Joel Africa', email: 'jafrica@planit.net.au', mobile: '+61861093800', title: 'STTA', role: 'Senior Technical Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('April 20, 2015'))
Employee.create(division: 'Technical', name: 'Mahabalesh Patige', email: 'mpatige@planit.net.au', mobile: '+61861093800', title: 'TTA', role: 'Technical Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('March 3, 2014'))
Employee.create(division: 'Technical', name: 'Patric Caceres', email: 'pcaceres@planit.net.au', mobile: '+61861093800', title: 'TTA', role: 'Technical Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('April 7, 2015'))
Employee.create(division: 'Technical', name: 'Phil Jonhson', email: 'pjonhson@planit.net.au', mobile: '+61861093800', title: 'STTC', role: 'Senior Technical Test Consultant', assigned: false, active: false, joined_company_at: Date.parse('January 4, 2016'))
# Employee.create(division: 'Functional', name: 'Caroline Carder', email: 'ccarder@planit.net.au', mobile: '+61415170400', title: 'PTC', role: 'Senior Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('October 20, 2014'))
# Employee.create(division: 'Functional', name: 'Jason Stannage', email: 'jstannage@planit.net.au', mobile: '+61451125077', title: 'PTC', role: 'Senior Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('September 25, 2015'))
# Employee.create(division: 'Functional', name: 'Kevin Chapman', email: 'kchapman@planit.net.au', mobile: '+61861093800', title: 'STC', role: 'Senior Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('November 10, 2014'))
# Employee.create(division: 'Functional', name: 'Mo Abdou', email: 'mabdou@planit.net.au', mobile: '+61861093800', title: 'STC', role: 'Senior Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('December 8, 2014'))
# Employee.create(division: 'Functional', name: 'Nikesh Doshi', email: 'ndoshi@planit.net.au', mobile: '+61861093800', title: 'TC', role: 'Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('June 9, 2014'))
# Employee.create(division: 'Functional', name: 'Bryan Tan', email: 'btan@planit.net.au', mobile: '+61861093800', title: 'TC', role: 'Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('December 13, 2013'))
# Employee.create(division: 'Functional', name: 'Michelle Hutton', email: 'mhutton@planit.net.au', mobile: '+61861093800', title: 'TC', role: 'Test Consultant', assigned: false, active: true, joined_company_at: Date.parse('October 31, 2010'))
# Employee.create(division: 'Functional', name: 'Glendy Hou', email: 'ghou@planit.net.au', mobile: '+61861093800', title: 'TL', role: 'Test Lead', assigned: false, active: true, joined_company_at: Date.parse('April 29, 2013'))
# Employee.create(division: 'Functional', name: 'Slawomir Stanik', email: 'sstanik@planit.net.au', mobile: '+61861093800', title: 'STA', role: 'Senior Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('May 5, 2014'))
# Employee.create(division: 'Functional', name: 'Kishore Vidyadharan', email: 'kvidyadharan@planit.net.au', mobile: '+61861093800', title: 'STA', role: 'Senior Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('May 26, 2014'))
# Employee.create(division: 'Functional', name: 'Lucy Jones', email: 'ljones@planit.net.au', mobile: '+61861093800', title: 'STA', role: 'Senior Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('February 17, 2014'))
# Employee.create(division: 'Functional', name: 'Merisa Adams', email: 'madams@planit.net.au', mobile: '+61861093800', title: 'STA', role: 'Senior Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('November 1, 2013'))
# Employee.create(division: 'Functional', name: 'Sarah Coster', email: 'scoster@planit.net.au', mobile: '+61861093800', title: 'TA', role: 'Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('August 12, 2013'))
# Employee.create(division: 'Functional', name: 'Echo Xia', email: 'exia@planit.net.au', mobile: '+61861093800', title: 'TA', role: 'Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('July 21, 2014'))
# Employee.create(division: 'Functional', name: 'Baljeet Virk', email: 'bvirk@planit.net.au', mobile: '+61861093800', title: 'TA', role: 'Test Analyst', assigned: false, active: true, joined_company_at: Date.parse('August 8, 2014'))
Customer.create!(name: 'Planit Sydney', fiscal_name: 'Planit Test Management Solutions Pty Ltd', abn: '61 079 209 135')
Customer.create!(name: 'Planit Melbourne', fiscal_name: 'Planit Test Management Solutions Pty Ltd', abn: '61 079 209 135')
Customer.create!(name: 'Planit Perth', fiscal_name: 'Planit Test Management Solutions Pty Ltd', abn: '61 079 209 135')
Customer.create!(name: 'Planit Brisbane', fiscal_name: 'Planit Test Management Solutions Pty Ltd', abn: '61 079 209 135')

Customer.create!(name: 'HBF', fiscal_name: 'HBF Health Limited', abn: '11 126 884 786')
Customer.create!(name: 'BHPBIO', fiscal_name: 'BHP BILLITON IRON ORE PTY. LTD.', abn: '46 008 700 981')
Customer.create!(name: 'RACWA', fiscal_name: 'RACWA Holdings Pty Ltd', abn: '60 008 985 877')
Customer.create!(name: 'RACI', fiscal_name: 'RAC Insurance Pty Ltd', abn: '59 094 685 882')
Customer.create!(name: 'ASG', fiscal_name: 'ASG Group Limited', abn: '57 070 045 117')
Customer.create!(name: 'ECU', fiscal_name: 'Edith Cowan University', abn: '54 361 485 361')
Customer.create!(name: 'WA Police', fiscal_name: 'Western Australia Police', abn: '91 724 684 688')

Contact.create!(name: 'Sally Hanna', email: 'sally.hanna@hbf.com.au', company: 'HBF')
Contact.create!(name: 'Lesley Bremmer Bell', email: 'lesley.bremnerbell@hbf.com.au')
Contact.create!(name: 'Sandra Albin', email: 'sandra.albin@hbf.com.au', company:'HBF')

Contact.create!(name: 'Paul Ward', email: 'paul.ward2@bhpbilliton.com', company: 'BHPBIO')
Contact.create!(name: 'Dominic Sabatino', email: 'dominic.sabatino@bhpbio.com', company: 'BHPBIO')
Contact.create!(name: 'Lynda Hennessy', email: 'lynda.hennessy@bhpbio.com', company: 'BHPBIO')
